ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER francisco
IDENTIFIED BY francisco
DEFAULT TABLESPACE system
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON system;

GRANT CONNECT, RESOURCE to francisco;
GRANT CREATE SESSION to francisco;